/*! Lofty v0.1 beta Classic http://lofty.fangdeng.org/ MIT*/
(function(b){if(!b.lofty){var d={},a=function(e,f,g){if(!d[e]){g||(g=f,f=[]);if("function"===typeof g){for(var b=[],m=0,l=f.length;m<l;m++)b.push(d[f[m]]);g=g.apply(a,b)}d[e]=g||1}},f=function(e){return d[e]};a.version="0.1";a.cache={parts:d};a("global",b);a("require",function(){return f});b.lofty=a}})(this);
lofty("lang",function(){var b={}.toString,d=Array.prototype,a={isFunction:function(f){return"[object Function]"===b.call(f)},isArray:Array.isArray||function(f){return"[object Array]"===b.call(f)},isString:function(f){return"string"===typeof f},forEach:d.forEach?function(f,e,a){f.forEach(e,a)}:function(a,e,b){for(var g=0,d=a.length;g<d;g++)e.call(b,a[g],g,a)},map:d.map?function(a,e,b){return a.map(e,b)}:function(f,e,b){var g=[];a.forEach(f,function(a,f,d){g.push(e.call(b,a,f,d))});return g},indexOf:d.indexOf?
function(a,e){return a.indexOf(e)}:function(a,e){for(var b=0,g=a.length;b<g;b++)if(a[b]===e)return b;return-1}};return a});lofty("event",function(){var b=this.cache.events={},d=[].slice,a={on:function(a,e){(b[a]||(b[a]=[])).push(e)},emit:function(a){var e=d.call(arguments,1),j=b[a],g,h=0;if(j)for(;g=j[h++];)g.apply(null,e)},off:function(a){b[a]&&delete b[a]}};this.on=a.on;this.off=a.off;return a});
lofty("config",["lang"],function(b){var d=this.cache,a=d.config={},f=d.configRules={},d={addRule:function(a,b){f[a]={rule:b,keys:[]};return this},addItem:function(a,b){f[b]&&f[b].keys.push(a);return this}};d.addRule("object",function(a,b,g){if(a){for(var d in g)a[d]=g[d];return!0}return!1}).addRule("array",function(a,b,d){a?a.push(d):this[b]=[d];return!0});this.config=function(e){if(b.isString(e))return a[e];for(var d in e){var g=e[d],h=a[d],m=d,l=g,k=!1,c=void 0,n=void 0;for(n in f)if(k)break;else c=
f[n],k=-1<b.indexOf(c.keys,m)&&c.rule.call(a,h,m,l);k||(a[d]=g)}};return d});lofty("alias",["config","event"],function(b,d){var a=this.cache.config;b.addItem("alias","object");return function(b){var e=a.alias,j;if(e&&(j=e[b.id]))b.id=j;d.emit("alias",b)}});
lofty("module",["global","lang","event","alias"],function(b,d,a,f){var e=[],j=0,g=this.cache.modules={},h={get:function(c){c={id:c};f(c);return g[c.id]},has:function(c){return h.get(c)||l[c]?!0:!1},hasDefine:function(c){return g[c]?!0:!1},isAnon:function(c){return""===c.id},save:function(c){g[c._id||c.id]=c},autocompile:function(c){h.isAnon(c)&&h.compile(c)},compile:function(c){try{if(d.isFunction(c.factory)){var e=[],b=c.deps;d.isArray(b)&&d.forEach(b,function(a){var b;a=(b=l[a])?b(c):h.require(a,
c);e.push(a)});var g=c.factory.apply(null,e);void 0!==g?c.exports=g:c.entity&&c.entity.exports&&(c.exports=c.entity.exports);c.entity&&delete c.entity}else void 0!==c.factory&&(c.exports=c.factory);a.emit("compiled",c)}catch(m){a.emit("compileFail",m,c)}},require:function(c){var b=h.get(c);b?(b.compiled||(b.compiled=!0,h.compile(b)),a.emit("required",b),c=b.exports):(/\.css(?:\?|$)/.test(c)||a.emit("requireFail",{id:c}),c=null);return c}},m=function(c,a,b){this.id=c;this.deps=a||[];this.factory=b;
this.exports={};""===c&&(c="__!_lofty_anonymous_"+j,j++,this._id=c)},l={require:function(){function c(c){return h.require(c)}a.emit("makeRequire",c);return c},exports:function(c){return c.exports},module:function(c){c.entity={id:c.id,exports:c.exports};return c.entity}},k=b.define;this.noConflict=function(){b.define=k};this.define=function(c,b,g){var f;f=arguments.length;1===f?(g=c,c=""):2===f&&(g=b,b=e,d.isString(c)||(b=c,c=""));if(h.hasDefine(c))return a.emit("existed",{id:c}),null;f=new m(c,b,
g);a.emit("define",f);h.save(f);h.autocompile(f)};b.define=this.define;return h});
lofty("loader",["global"],function(b){var d=this.cache.config,a=b.document,f=/\.css(?:\?|$)/,e=/loaded|complete|undefined/,j=536>1*b.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),g=a&&(a.head||a.getElementsByTagName("head")[0]||a.documentElement),h=a.getElementsByTagName("base")[0],m=function(a,b){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;b&&b()}};return function(l,k){var c;if(f.test(l)){var n=c=a.createElement("link");if(j||!("onload"in n)){var q=a.createElement("img");
q.onerror=function(){k();q.onerror=null;q=void 0};q.src=l}else n.onload=n.onreadystatechange=function(){e.test(n.readyState)&&(n.onload=n.onreadystatechange=n.onerror=null,n=void 0,k&&k())},m(n,k);c.rel="stylesheet";c.href=l}else{var p=c=a.createElement("script");p.onload=p.onreadystatechange=function(a){a=a||b.event;if("load"===a.type||e.test(p.readyState))p.onload=p.onreadystatechange=p.onerror=null,d.debug||g.removeChild(p),p=void 0,k&&k()};m(p,k);c.async=!0;c.src=l}d.charset&&(c.charset=d.charset);
h?g.insertBefore(c,h):g.appendChild(c)}});
lofty("id2url",["global","event","config","alias"],function(b,d,a,f){var e=this.cache.config,j=/\?|\.(?:css|js)$|\/$/,g=/^https?:\/\//,h=(new Date).getTime();b=b.document.getElementsByTagName("script");b=b[b.length-1];b=(b.hasAttribute?b.src:b.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);e.baseUrl=b[0];a.addItem("resolve","array").addItem("stamp","object");return function(a){f(a);var b=e.resolve,k;if(b)for(var c=0,n=b.length;c<n&&!(k=b[c](a.id),k!==a.id);c++);a.url=k?k:a.id;d.emit("resolve",
a);g.test(a.url)||(a.url=e.baseUrl+a.url);!j.test(a.url)&&(a.url+=".js");b=e.hasStamp?h:null;if(k=e.stamp)for(var q in k)if(RegExp(q).test(a.id)){b=k[q];break}b&&(a.url+="?lofty.stamp="+b);d.emit("id2url",a)}});
lofty("request",["global","event","loader","id2url"],function(b,d,a,f){var e=this.cache,j=e.config,g=e.assets={};j.loadTimeout=1E4;var h=function(a,b){if(!a.timeout){var e,c;b?(a.status=2,c=a.callQueue):(a.status=-1,c=a.errorQueue);for(;e=c.shift();)e()}};return function(e,l,k){var c;e={id:e};f(e);c=g[e.url]||(g[e.url]=e);2===c.status?l&&l():(c.callQueue?c.callQueue.push(l):c.callQueue=[l],c.errorQueue?c.errorQueue.push(k):c.errorQueue=[k],1!==c.status&&(c.status=1,c.timer=setTimeout(function(){d.emit("requestTimeout",
c);h(c,!1);c.timeout=!0},j.loadTimeout),a(c.url,function(){b.clearTimeout(c.timer);d.emit("requested",c);h(c,!0)})))}});
lofty("deferred",function(){var b=function(){},d=function(a){var d=this,e=[],j=0,g=0;a=a||0;var h=function(){j+g===a&&m()},m=function(){d.then=!g?function(a){a&&a()}:function(a,c){c&&c()};m=b;l(!g?0:1);l=b;e=[]},l=function(a){for(var c,b=0;c=e[b++];)(c=c[a])&&c()};this.then=function(a,b){e.push([a,b])};this.resolve=function(){j++;h()};this.reject=function(){g++;h()};h()};return function(){for(var a=new d(arguments.length),b,e=0;b=arguments[e++];)b(a);return a}});
lofty("use",["lang","event","module","request","deferred"],function(b,d,a,f,e){var j={fetch:function(d,f){j.get(d,function(){e.apply(null,b.map(d,function(b){return function(e){var d=a.get(b);d?j.fetch(d.deps,function(){e.resolve()}):e.resolve()}})).then(f)})},get:function(d,h,j){e.apply(null,b.map(d,function(b){return function(e){a.has(b)?e.resolve():f(b,function(){e.resolve()},function(){e.reject()})}})).then(h,j)}};d.on("makeRequire",function(e){e.use=function(e,d){b.isArray(e)||(e=[e]);j.fetch(e,
function(){var g=b.map(e,function(b){return a.require(b)});d&&d.apply(null,g)})}});return j});lofty("amd",["module","use"],function(b,d){var a=this.cache.config;a.amd=!0;b.autocompile=function(f){b.isAnon(f)&&(a.amd?d.fetch(f.deps,function(){b.compile(f)}):b.compile(f))}});
lofty("appframe",["global","config"],function(b,d){var a=this;a.appframe=function(f){f=(b[f]={define:a.define,log:function(){a.log.apply(null,arguments)},config:a.config,on:a.on,off:a.off}).config;f.addRule=d.addRule;f.addItem=d.addItem}});
lofty("log",["global","console","request","require"],function(b,d,a,f){var e=this,j=e.log=function(){},g=b.console;return{create:function(b){e.log=b?g&&g.warn?function(a,b){g[b||"log"](a)}:function(b,e){d?d(b,e):a&&a("lofty/kernel/console",function(){d||(d=f("console"));d(b,e)})}:j},log:function(a){e.log(a,"log")},warn:function(a){e.log(a,"warn")}}});
lofty("debug",["config","log","event"],function(b,d,a){b.addRule("debug",function(a,b,g){d.create(g);this[b]=g;return!0}).addItem("debug","debug");var f=this.cache.config;a.on("existed",function(a){d.warn(a.id+": already exists.")});a.on("compiled",function(a){d.log((a._id?a._id:a.id)+": compiled.")});a.on("compileFail",function(a){if(!f.hasCatch||f.debug)throw a;});a.on("required",function(a){!a.visits?a.visits=1:a.visits++;d.log(a.id+": required "+a.visits+".")});a.on("requireFail",function(a){d.warn(a.id+
": does not exist.")});a.on("requested",function(a){d.log(a.url+" requested")});a.on("requestTimeout",function(a){d.warn("request "+a.url+" timeout.")})});
lofty("alicn",["global","event"],function(b,d){var a=/\.css(?:\?|$)/,f=/([a-z])([A-Z])/g;d.on("resolve",function(a){a.url=a.url.replace(f,function(a,b,e){return b+"-"+e}).toLowerCase()});this.config({amd:!1,resolve:function(b){var d=b.split("/"),f=d[0],h=a.test(b)?"css/":"js/";switch(f){case "lofty":case "gallery":b="fdevlib/"+h+b;break;case "sys":b="sys/"+h+d.slice(1).join("/")}return b},debug:0<b.location.href.indexOf("lofty.debug=true")})});
