/*! Lofty v0.1 beta Classic http://lofty.fangdeng.org/ MIT*/
(function(c){if(!c.lofty){var e={},b=function(a,g,j){if(!e[a]){j||(j=g,g=[]);if("function"===typeof j){for(var c=[],l=0,m=g.length;l<m;l++)c.push(e[g[l]]);j=j.apply(b,c)}e[a]=j||1}},a=function(a){return e[a]};b.version="0.1";b.cache={parts:e};b("global",c);b("require",function(){return a});c.lofty=b}})(this);
lofty("lang",function(){var c={}.toString,e=Array.prototype,b={isFunction:function(a){return"[object Function]"===c.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===c.call(a)},isString:function(a){return"string"===typeof a},forEach:e.forEach?function(a,f,b){a.forEach(f,b)}:function(a,f,b){for(var c=0,e=a.length;c<e;c++)f.call(b,a[c],c,a)},map:e.map?function(a,f,b){return a.map(f,b)}:function(a,f,c){var e=[];b.forEach(a,function(a,b,m){e.push(f.call(c,a,b,m))});return e},indexOf:e.indexOf?
function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,e=a.length;c<e;c++)if(a[c]===b)return c;return-1}};return b});lofty("event",function(){var c=this.cache.events={},e=[].slice;return{on:function(b,a){(c[b]||(c[b]=[])).push(a)},emit:function(b){var a=e.call(arguments,1),f=c[b],g,j=0;if(f)for(;g=f[j++];)g.apply(null,a)},off:function(b){c[b]&&delete c[b]}}});
lofty("config",["lang"],function(c){var e=this.cache,b=e.config={},a=e.configRules={},e={addRule:function(b,c){a[b]={rule:c,keys:[]};return this},addItem:function(b,c){a[c]&&a[c].keys.push(b);return this}};e.addRule("object",function(a,b,c){if(a){for(var e in c)a[e]=c[e];return!0}return!1}).addRule("array",function(a,b,c){a?a.push(c):this[b]=[c];return!0});this.config=function(e){for(var g in e){var j=e[g],k=b[g],l=g,m=j,h=!1,d=void 0,n=void 0;for(n in a)if(h)break;else d=a[n],h=-1<c.indexOf(d.keys,
l)&&d.rule.call(b,k,l,m);h||(b[g]=j)}};return e});lofty("alias",["config","event"],function(c,e){var b=this.cache.config;c.addItem("alias","object");return function(a){var c=b.alias,g;if(c&&(g=c[a.id]))a.id=g;e.emit("alias",a)}});
lofty("module",["global","lang","event","alias"],function(c,e,b,a){var f=[],g=0,j=this.cache.modules={},k={get:function(d){d={id:d};a(d);return j[d.id]},has:function(d){return k.get(d)||m[d]?!0:!1},hasDefine:function(d){return j[d]?!0:!1},isAnon:function(d){return""===d.id},save:function(d){j[d._id||d.id]=d},autocompile:function(d){k.isAnon(d)&&k.compile(d)},compile:function(d){try{if(e.isFunction(d.factory)){var a=[],c=d.deps;e.isArray(c)&&e.forEach(c,function(b){var c;b=(c=m[b])?c(d):k.require(b,
d);a.push(b)});var f=d.factory.apply(null,a);void 0!==f?d.exports=f:d.entity&&d.entity.exports&&(d.exports=d.entity.exports);d.entity&&delete d.entity}else void 0!==d.factory&&(d.exports=d.factory);b.emit("compiled",d)}catch(l){b.emit("compileFail",l,d)}},require:function(d){var a=k.get(d);a?(a.compiled||(a.compiled=!0,k.compile(a)),b.emit("required",a),d=a.exports):(b.emit("requireFail",{id:d}),d=null);return d}},l=function(d,a,b){this.id=d;this.deps=a||[];this.factory=b;this.exports={};""===d&&
(d="__!_lofty_anonymous_"+g,g++,this._id=d)},m={require:function(){function d(d){return k.require(d)}b.emit("makeRequire",d);return d},exports:function(d){return d.exports},module:function(d){d.entity={id:d.id,exports:d.exports};return d.entity}},h=c.define;this.noConflict=function(){c.define=h};this.define=function(d,a,c){var h;h=arguments.length;1===h?(c=d,d=""):2===h&&(c=a,a=f,e.isString(d)||(a=d,d=""));if(k.hasDefine(d))return b.emit("existed",{id:d}),null;h=new l(d,a,c);b.emit("define",h);k.save(h);
k.autocompile(h)};c.define=this.define;return k});
lofty("loader",["global"],function(c){var e=this.cache.config,b=c.document,a=/\.css(?:\?|$)/,f=/loaded|complete|undefined/,g=536>1*c.navigator.userAgent.replace(/.*AppleWebKit\/(\d+)\..*/,"$1"),j=b&&(b.head||b.getElementsByTagName("head")[0]||b.documentElement),k=b.getElementsByTagName("base")[0],l=function(a,b){a.onerror=function(){a.onload=a.onreadystatechange=a.onerror=null;a=void 0;b&&b()}};return function(m,h){var d;if(a.test(m)){var n=d=b.createElement("link");if(g||!("onload"in n)){var q=b.createElement("img");
q.onerror=function(){h();q.onerror=null;q=void 0};q.src=m}else n.onload=n.onreadystatechange=function(){f.test(n.readyState)&&(n.onload=n.onreadystatechange=n.onerror=null,n=void 0,h&&h())},l(n,h);d.rel="stylesheet";d.href=m}else{var p=d=b.createElement("script");p.onload=p.onreadystatechange=function(a){a=a||c.event;if("load"===a.type||f.test(p.readyState))p.onload=p.onreadystatechange=p.onerror=null,e.debug||j.removeChild(p),p=void 0,h&&h()};l(p,h);d.async=!0;d.src=m}e.charset&&(d.charset=e.charset);
k?j.insertBefore(d,k):j.appendChild(d)}});
lofty("id2url",["global","event","config","alias"],function(c,e,b,a){var f=this.cache.config,g=/\?|\.(?:css|js)$|\/$/,j=/^https?:\/\//,k=(new Date).getTime();c=c.document.getElementsByTagName("script");c=c[c.length-1];c=(c.hasAttribute?c.src:c.getAttribute("src",4)).match(/([\w]+)\:\/\/([\w|\.|\:]+)\//i);f.baseUrl=c[0];b.addItem("resolve","array").addItem("stamp","object");return function(b){a(b);var c=f.resolve,h;if(c)for(var d=0,n=c.length;d<n&&!(h=c[d](b.id),h!==b.id);d++);b.url=h?h:b.id;e.emit("resolve",
b);j.test(b.url)||(b.url=f.baseUrl+b.url);!g.test(b.url)&&(b.url+=".js");c=f.hasStamp?k:null;if(h=f.stamp)for(var q in h)if(RegExp(q).test(b.id)){c=h[q];break}c&&(b.url+="?lofty.stamp="+c);e.emit("id2url",b)}});
lofty("request",["global","event","loader","id2url"],function(c,e,b,a){var f=this.cache,g=f.config,j=f.assets={};g.loadTimeout=1E4;var k=function(a,b){if(!a.timeout){c.clearTimeout(a.timer);e.emit("requested",a);var f,d;b?(a.status=2,d=a.callQueue):(a.status=-1,d=a.errorQueue);for(;f=d.shift();)f()}};return function(c,f,h){var d;c={id:c};a(c);d=j[c.url]||(j[c.url]=c);2===d.status?f&&f():(d.callQueue?d.callQueue.push(f):d.callQueue=[f],d.errorQueue?d.errorQueue.push(h):d.errorQueue=[h],1!==d.status&&
(d.status=1,d.timer=setTimeout(function(){d.timeout=!0;e.emit("requestTimeout",d);k(d,!1)},g.loadTimeout),b(d.url,function(){k(d,!0)})))}});
lofty("deferred",function(){var c=function(){},e=function(b){var a=this,e=[],g=0,j=0;b=b||0;var k=function(){g+j===b&&l()},l=function(){a.then=!j?function(a){a&&a()}:function(a,b){b&&b()};l=c;m(!j?0:1);m=c;e=[]},m=function(a){for(var b,c=0;b=e[c++];)(b=b[a])&&b()};this.then=function(a,b){e.push([a,b])};this.resolve=function(){g++;k()};this.reject=function(){j++;k()};k()};return function(){for(var b=new e(arguments.length),a,c=0;a=arguments[c++];)a(b);return b}});
lofty("use",["lang","event","module","request","deferred"],function(c,e,b,a,f){var g={fetch:function(a,e){g.get(a,function(){f.apply(null,c.map(a,function(a){return function(c){var e=b.get(a);e?g.fetch(e.deps,function(){c.resolve()}):c.resolve()}})).then(e)})},get:function(e,k,g){f.apply(null,c.map(e,function(c){return function(e){b.has(c)?e.resolve():a(c,function(){e.resolve()},function(){e.reject()})}})).then(k,g)}};e.on("makeRequire",function(a){a.use=function(a,e){c.isArray(a)||(a=[a]);g.fetch(a,
function(){var f=c.map(a,function(a){return b.require(a)});e&&e.apply(null,f)})}});return g});lofty("amd",["module","use"],function(c,e){var b=this.cache.config;b.amd=!0;c.autocompile=function(a){c.isAnon(a)&&(b.amd?e.fetch(a.deps,function(){c.compile(a)}):c.compile(a))}});
lofty("appframe",["global","event","config"],function(c,e,b){var a=this;a.appframe=function(f){f=(c[f]={define:a.define,log:function(){a.log.apply(null,arguments)},config:a.config,on:e.on,off:e.off}).config;f.addRule=b.addRule;f.addItem=b.addItem}});
lofty("log",["global","console","request","require"],function(c,e,b,a){var f=this,g=f.log=function(){};return{create:function(j){f.log=j?c.console?function(a,b){c.console[b||"log"](a)}:function(c,f){e?e(c,f):b&&b("lofty/kernel/console",function(){e||(e=a("console"));e(c,f)})}:g},log:function(a){f.log(a,"log")},warn:function(a){f.log(a,"warn")}}});
lofty("debug",["config","log","event"],function(c,e,b){c.addRule("debug",function(a,b,c){e.create(c);this[b]=c;return!0}).addItem("debug","debug");b.on("existed",function(a){e.warn(a.id+": already exists.")});b.on("compiled",function(a){e.log((a._id?a._id:a.id)+": compiled.")});b.on("compileFail",function(a,b){e.warn((b._id?b._id:b.id)+": "+a.message)});b.on("required",function(a){!a.visits?a.visits=1:a.visits++;e.log(a.id+": required "+a.visits+".")});b.on("requireFail",function(a){e.warn(a.id+": does not exist.")});
b.on("requested",function(a){e.log(a.url+" requested")});b.on("requestTimeout",function(a){e.warn("request "+a.url+" timeout.")})});
lofty("alicn",["global","event"],function(c,e){var b=/\.css(?:\?|$)/,a=/([a-z])([A-Z])/g;e.on("resolve",function(b){b.url=b.url.replace(a,function(a,b,c){return b+"-"+c}).toLowerCase()});this.config({amd:!1,hasStamp:!0,resolve:function(a){var c=a.split("/"),e=c[0],k=b.test(a)?"css/":"js/";switch(e){case "lofty":case "gallery":a="fdevlib/"+k+a;break;case "sys":a="sys/"+k+c.slice(1).join("/")}return a},debug:0<c.location.href.indexOf("lofty.debug=true")})});
